version: "3.2"

networks:
  app-tier:
    driver: bridge

services:
  nodejs:
    build:
      context: .
    image: boaventurathomas/desafio-dev-api-rest
    networks:
      - app-tier
    environment:
      - SERVER_PORT=3000
      - MODE=DEV
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_DATABASE=desafio-dev-api-rest
      - DB_SYNCHRONIZE=false
      - DB_LOGGING=false
    volumes:
      - ./www/:/var/www/html/
    ports:
      - "3000:3000"
    container_name: nodejs-app
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    # restart: always
    ports:
      - "3306:3306"
    networks:
      - app-tier
    environment:
      - MYSQL_DATABASE=desafio-dev-api-rest
      - MYSQL_ROOT_PASSWORD=root
    container_name: mysql-app
    volumes:
      - "./scripts/desafio-dev-api-rest.sql:/docker-entrypoint-initdb.d/1.sql"
